/// <reference types="@sveltejs/kit" />

/**
 * Runtime types come from `src/worker-configuration.d.ts`, generated by
 * `npm run cf-typegen` from `wrangler.jsonc`. Rerun it after changing a binding
 * so the types cannot drift from what is deployed.
 */
declare global {
  namespace App {
    interface Platform {
      env: Partial<Env>;
      cf?: IncomingRequestCfProperties;
      ctx: ExecutionContext;
    }
  }
}

export {};
